name: example
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: cjl_macbook <cjl_spy@163.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  image_metadata_getter:
    path: ../packages/image_metadata_getter

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
